#ifndef __Battle_RES_H__m
#define __Battle_RES_H__

#include "cocos2d.h"


//定义平台路径分隔符
/*define PLAYFORM_SEPERATOR  \\\*/

//定义资源路转换宏
#define	_FULLPATH_STR(path)  #path 
#define  FULLPATH_STR(path) _FULLPATH_STR(path)
//#define _PATH_ATTACH_SEPERATOR(pathup,seperator,path)  pathup##seperator##path  //路径链接宏
//#define  PATH_ATTACH_SEPERATOR(pathup,seperator,path) _PATH_ATTACH_SEPERATOR(pathup,seperator,path) 
#ifdef _WIN32
	#define _PATH_ATTACH(pathup,path)  pathup\\path
#else
	#define _PATH_ATTACH(pathup,path)  pathup/path
#endif

#define PATH_ATTACH(pathup,path)  _PATH_ATTACH(pathup,path)  //将平台路径分隔符添加在pathup以及path之间


USING_NS_CC;
//分辨率
#define UI_NACTIVE_BK_HEIGHT (640.0f)  //纵向原始分辨率

#define BATTLEMAP_TMX_TAG  10001 //TMX标签
//游戏音乐存放路径
#define MUSIC_FILE_PATH Music
#define MUSIC_FILE_POSTION 
#define MUSIC_FILE_PATH_NAME FULLPATH_STR(PATH_ATTACH(MUSIC_FILE_PATH,MUSIC_FILE_POSTION))
#define MUSIC_TITLE_FILE_NAME 4
#define MUSIC_TITLE_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(MUSIC_FILE_PATH,MUSIC_TITLE_FILE_NAME))
#define MUSIC_BATTLE1_FILE_NAME battle1
#define MUSIC_BATTLE1_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(MUSIC_FILE_PATH,MUSIC_BATTLE1_FILE_NAME))
#define MUSIC_BATTLE2_FILE_NAME battle2
#define MUSIC_BATTLE2_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(MUSIC_FILE_PATH,MUSIC_BATTLE2_FILE_NAME))

//战场存档文件名
#define  SAVE_BATTLE_FILE_NAME "BattleSave.save"
//存档数据标识名
#define  SAVE_DATA_STAGE_NAME "STAGE"


//游戏数据存放位置
#define DATA_FILE_PATH DATA
//角色数据存放文件名
#define DATA_CHARACTER_FILE_NAME CharactersData.xml
#define DATA_SKILL_FILE_NAME SkillsData.xml
#define DATA_CHARACTER_FULLPATH  FULLPATH_STR(PATH_ATTACH(DATA_FILE_PATH,DATA_CHARACTER_FILE_NAME))
#define DATA_SKILL_FULLPATH  FULLPATH_STR(PATH_ATTACH(DATA_FILE_PATH,DATA_SKILL_FILE_NAME))
#define DATA_ABILITY_FILE_NAME AbilitiesData.xml 
#define DATA_ABILITY_FULLPATH  FULLPATH_STR(PATH_ATTACH(DATA_FILE_PATH,DATA_ABILITY_FILE_NAME))
#define EVENTHANDLER_DOCUMENT_NAME EventHandler.xml
#define EVENTHANDLER_DOCUMENT_FULLPATH FULLPATH_STR(PATH_ATTACH(DATA_FILE_PATH,EVENTHANDLER_DOCUMENT_NAME))


//角色数据名称标识
#define DATA_ATTRIBUTE_ID "ID"

#define DATA_CHARACTER_NAME "NAME"
#define DATA_CHARACTER_MAXHP  "MAXHP"
#define DATA_CHARACTER_HP  "HP"
#define DATA_CHARACTER_HP_PLUS  "HP_PLUS"
#define DATA_CHARACTER_SP  "SP"
#define DATA_CHARACTER_MAXSP "MAXSP"
#define DATA_CHARACTER_SP_PLUS  "SP_PLUS"
#define DATA_CHARACTER_STR  "STR"
#define DATA_CHARACTER_STR_PLUS  "STR_PLUS"
#define DATA_CHARACTER_DEF  "DEF"
#define DATA_CHARACTER_DEF_PLUS  "DEF_PLUS"
#define DATA_CHARACTER_MAG  "MAG"
#define DATA_CHARACTER_MAG_PLUS  "MAG_PLUS"
#define DATA_CHARACTER_LUK  "LUK"
#define DATA_CHARACTER_LUK_PLUS  "LUK_PLUS"
#define DATA_CHARACTER_SPD  "SPD"
#define DATA_CHARACTER_SPD_PLUS  "SPD_PLUS"
#define DATA_CHARACTER_DEX  "DEX"
#define DATA_CHARACTER_DEX_PLUS  "DEX_PLUS"
#define DATA_CHARACTER_MOVE  "MOVE"
#define DATA_CHARACTER_TYPE  "TYPE"
#define DATA_CHARACTER_LEVEL "LEVEL"
#define DATA_CHARACTER_EXP "EXP"
#define DATA_CHARACTER_FORCE "FORCE"
#define DATA_CHARACTER_X "X"
#define DATA_CHARACTER_Y "Y"
#define DATA_CHARACTER_SKILLS "SKILLS"
#define DATA_CHARACTER_SKILL "SKILL"
#define DATA_CHARACTER_MAXRANGE "MAXRANGE"
#define DATA_CHARACTER_MINRANGE "MINRANGE"

//技能数据名称标识
#define DATA_SKILL_NAME	"NAME"
#define DATA_SKILL_TYPE	"TYPE"
#define DATA_SKILL_DAMAGE	"DAMAGE"
#define DATA_SKILL_HEALING	"HEALING"
#define DATA_SKILL_RANGE	"RANGE"
#define DATA_SKILL_SUBRANGE	"SUBRANGE"
#define DATA_SKILL_HPCOST	"HPCOST"
#define DATA_SKILL_EFFECT	"EFFECT"

//技能类型
#define SKILL_TYPE_DAMAGE	1
#define SKILL_TYPE_HEALING	2
#define SKILL_TYPE_DAMAGE_AND_HEALING 3



//地图角色动画速度
#define _MAPSPRITE_FLESH_RATE_ (0.1f)//刷新延迟
#define _MAPSPRITE_PER_FRAME_ (1.0f)//每走一个方格的行动动画重复次数
#define _MAPSPRITE_DUR_ (4.0f)*_MAPSPRITE_PER_FRAME_ *_MAPSPRITE_FLESH_RATE_ //动画总时间  常数代表帧数.


//BattleMap和它的兄弟layer的Tag
#define MAX_LAYER_ZORDER 2000			//最大Z轴优先度

#define LAYER_BATTLEMAP_LAYER_ID 10001  //战斗地图层
#define LAYER_MAINMENU_LAYER_ID 10002   //主菜单层
#define LAYER_ENDTURN_LAYER_ID 10003    //确认回合结束
#define LAYER_INTERFACE_MENU_ID 10004		//界面菜单
#define LAYER_DUAL_LAYER_ID 10005       //决斗场景层
#define LAYER_TURNTASS_LAYER_ID 10006			//结束回合
#define LAYER_SHOWRANGE_MENU_ID 10007  //显示范围菜单
#define LAYER_SHOWSTATUS_MENU_ID 10008 //显示角色状态
#define LAYER_STORY_LAYER_ID 10009 //故事场景界面
#define LAYER_SUBRANGE_ID 10100 //范围选择工具层
#define LAYER_DUEL_LAYER_ID 10010 //决斗场景ID
#define LAYER_DIALOG_LAYER_ID 100011//对话场景ID
#define LAYER_MAPNUMS_ID  10101 //地图数字BatchNode层
#define LAYER_MAPSKILLBACKGROUND_ID 10102//地图技能背景层
//#define LAYER_MAPCHARACER_BASED_ID 0//地图角色BATCHNODE的基础tag偏移量

#define UI_FILE_PATH UI //定义UI资源路径


//故事场景背景图片资源路径
#define STORY_BACKGROUND_FILE_NAME  story
#define STORY_BACKGROUND_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(SCENE_BACKGROUND_FILE_PATH,STORY_BACKGROUND_FILE_NAME))

//对话场景人物立绘图片资源路径
#define DIALOG_UI_FILE_NAME Dialog
#define DIALOG_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,DIALOG_UI_FILE_NAME))
#define DlALOG_DIALOG_FRAME_NAME "dialog"
#define DIALOG_FACE_FAME_NAME "Face"
//定义对话文本文件存放路径
#define DIALOG_WORD_FILE_NAME 
#define DIALOG_WORD_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(DATA_FILE_PATH,DIALOG_WORD_FILE_NAME))
//对话场景模式
#define DIALOG_MODE_STORY 1
#define DIALOG_MODE_BATTLE 2


//定义标题界面资源路径、背景图片名称、帧数
#define TITLE_BACKGROUND_FILE_PATH  Title
#define TITLE_BACKGROUND_FILE_NAME  title
#define TITLE_BACKGROUND_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(TITLE_BACKGROUND_FILE_PATH,TITLE_BACKGROUND_FILE_NAME))

#define MAX_TITLE_BACKGROUND_FRAME  20
#define TITLE_BACKGROUND_ANI_DUR 0.1f
//定义标题菜单资源路径、菜单图片名称
#define TITLE_MENU_FILE_PATH  Title
#define TITLE_MENU_FILE_NAME  TitleMenu
#define TITLE_MENU_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(TITLE_MENU_FILE_PATH,TITLE_MENU_FILE_NAME))
#define TTTLE_MENU_NEWGAME_LABEL_NAME "TitleNewGame"
#define TTTLE_MENU_CONTINUE_LABEL_NAME "TitleContinue"
#define TTTLE_MENU_LOADGAME_LABEL_NAME "TitleLoadGame"
#define TTTLE_MENU_QUITGAME_LABEL_NAME "TitleQuitGame"
//定义loading图标路径
#define LOADING_ICON_FILE_PATH  Loading
#define LOADING_ICON_FILE_NAME  SimpleLoading
#define LOADING_ICON_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(LOADING_ICON_FILE_PATH,LOADING_ICON_FILE_NAME))

#define LOADING_ICON_FRAME_NAME "SimpleLoading"
#define LOADING_ANIMATION_DUR 0.1f
//定义方块光标动画路径
#define SQUARE_ICON_FILE_PATH UI
#define SQUARE_ICON_FILE_NAME square
#define SQUARE_ICON_FILE_FULLPATH   FULLPATH_STR(PATH_ATTACH(SQUARE_ICON_FILE_PATH,SQUARE_ICON_FILE_NAME))

#define SQUARE_ICON_FRAME_NAME "square"
#define SQUARE_ANIMATION_DUR 0.1f

//定义决斗场景模式 
#define	DUELMODE_ATK_PLAYER 500
#define DUELMODE_ATK_ENERMY 501
#define DUELMODE_ATK_PLAYER_ONLY 502
#define DUELMODE_ATK_ENERMY_ONLY 503
#define DUELMODE_ATK_PLAYER_RANGE		504
#define DUELMODE_ATK_ENERMY_RANGE		505
#define DUELMODE_ATK_PLAYER_RANGE_ONLY  506
#define DUELMODE_ATK_ENERMY_RANGE_ONLY	507

//定义场景背景路径
#define SCENE_BACKGROUND_FILE_PATH SceneBack
#define DUEL_BACKGROUND_FILE_NAME DuelBK_Stage
#define DUEL_BACKGROUND_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(SCENE_BACKGROUND_FILE_PATH,DUEL_BACKGROUND_FILE_NAME))



//定义优先级

//定义战斗地图路径、资源文件名
#define STAGE_FILE_PATH Stage
#define STAGE_FILE_NAME stage
#define STAGE_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(STAGE_FILE_PATH,STAGE_FILE_NAME))
//地图角色的血条图片资源
#define HPBAR_FILE_NAME     HP_Bar
#define HPBAR_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,HPBAR_FILE_NAME))
#define HPOFF_FILE_NAME		HP_BarOff
#define HPOFF_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,HPOFF_FILE_NAME))
#define MAX_ANIMATION_FRAME  100     // 角色动作最大帧数
//地图角色图片文件  命名规则:角色文件名+角色ID+角色动作+动作编号+帧数标识+帧数
#define MAP_FILE_PATH   Map  //地图动画资源存放位置
#define MAPCHAR_FILE_NAME   bmc  //地图角色资源文件名
#define MAPCHAR_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(MAP_FILE_PATH,MAPCHAR_FILE_NAME))
#define MAPCHAR_FRAME_NAME "bmc"
#define MAPCHAR_ACTION_FILE_NAME "a"  //地图角色动作文件名
#define MAPCHAR_FRAME_COUNT_NAME "f"  //地图角色动作帧数文件名
#define ACTION_MAPSTAND   004	//角色站立动作
#define ACTION_MAPSTEPDOWN   104    //地图角色向下移动
#define ACTION_MAPSTEPUP     204	//地图角色向上移动
#define ACTION_MAPSTEPRIGHT     304	//地图角色向右移动
#define ACTION_MAPSTEPLEFT     404	//地图角色向左移动
#define ACTION_MAPSTAY        501  //地图角色待机
#define MAX_MAPCHAR_COUNT 14

//地图影子	
#define MAP_SHADOW_FRAME_NAME  "shadowFrame"
//地图技能动画资源
#define MAP_SKILL_FILE_NAME MapSkill
#define MAP_SKILL_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(MAP_FILE_PATH,MAP_SKILL_FILE_NAME))
#define MAP_SKILL_FRAME_NAME "mapskill"
#define MAP_SKILL_BACKGROUND_FRAME_NAME "BG"
#define MAP_SKILL_FRAME_COUNT_NAME "f"
//地图角色被击败动画
#define MAP_CHARACTER_VANISH_FILE_NAME MapCharacterVanish
#define MAP_CHARACTER_VANISH_FILE_FULLPATH FULLPATH_STR(PATH_ATTACH(MAP_FILE_PATH,MAP_CHARACTER_VANISH_FILE_NAME))
#define MAP_CHARACTER_VANISH_FRAME_NAME "vanish"
//地图技能动画帧数间隔
#define MAP_SKILL_FRAME_DUR 0.05f
//地图角色击败动画帧数间隔
#define MAP_CHARACTER_VANISH_FRAME_DUR 0.05f

//决斗场景角色图片文件，命名规则:角色文件名+角色ID+角色动作+动作编号+帧数标识+动作帧数
#define DUEL_FILE_PATH Duel
#define DUEL_CHAR_FILE_NAME dmc
#define DUEL_CHAR_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(DUEL_FILE_PATH,DUEL_CHAR_FILE_NAME))
#define DUEL_CHAR_FRAME_NAME "dmc"	//决斗场景角色文件名
#define DUEL_CHARSHADOW_FILE_NAME "dmcsh"   //决斗场景角色的影子文件名
#define DUEL_ACTION_FILE_NAME "a" //决斗角色动作文件名
#define DUEL_FRAME_FILE_NAME "f"	//决斗角色动作帧数文件名
//决斗“波”命名规则:“波”ID标识+波ID+波帧数标识+波帧数
#define DUEL_WAVE_FILE_NAME DuelWaves //决斗角色所产生的剑气、魔法光线等图片文件名
#define DUEL_WAVE_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(DUEL_FILE_PATH,DUEL_WAVE_FILE_NAME))
#define DUEL_WAVE_ID_NAME	"WaveID"//ID名
#define DUEL_WAVE_FRAME_NAME "wf"  //“波”帧数名
#define DUEL_UNWAVE_ID       -1  //无波
//决斗动作列表
#define DUEL_ATK_STYLE_FRAME  30
#define ACTION_DUEL_STAND 0
#define ACTION_DUEL_SKILL 1
#define ACTION_DUEL_ATK  2
#define ACTION_DUEL_RUN	3
//被攻击时有3种动画  请损伤 0  ~ 重损伤 2, 将这组数字作为*10位帧数调用
#define ACTION_DUEL_HIT 4
#define ACTION_DUEL_ATKSTANDBY 5
//决斗场景的数值条等UI
#define	DUEL_LAYERUI_FILE_NAME  DuelLayerUI
#define	DUEL_LAYERUI_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,DUEL_LAYERUI_FILE_NAME))
#define DUEL_LAYERUI_LEFTBARBK_NAME "leftBarBK"
#define DUEL_LAYERUI_RIGHTBARBK_NAME "rightBarBK"
#define DUEL_LAYERUI_LEFTHP_NAME "leftHP"
#define DUEL_LAYERUI_LEFTMP_NAME "leftMP"
#define DUEL_LAYERUI_RIGHTHP_NAME "rightHP"
#define DUEL_LAYERUI_RIGHTMP_NAME "rightMP"
//决斗场景位置宏
#define DUAL_STANDPOSITION 93


//决斗攻击动作段数表
#define DMC14_ATK_COUNT 1

//菜单

//主菜单
#define MAINMENU_MENU_FILE_NAME BattleMainMenu
#define	MAINMENU_MENU_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,MAINMENU_MENU_FILE_NAME))
#define MAINMENU_ENDTURN_LABEL_NAME "EndTurn"
#define MAINMENU_SAVE_LABEL_NAME "Save"
#define MAINMENU_LOAD_LABEL_NAME "Load"
#define MAINMENU_GOTOAIM_LABEL_NAME "GoToAim"
#define MAINMENU_SYSTEMCONFIG_LABEL_NAME "SystemConfig"
#define MAINMENU_TOVICTORY_LABEL_NAME "ToVictory"
#define MAINMENU_ENDGAME_LABEL_NAME "EndGame"
#define MAINMENU_TRANSPARENT_BACKGROUND_NAME "BackGround"
#define MAINMENU_BATTLEFIELDSTATUS_CONPONENT_NAME "BattleFieldStatus"
#define MAINMENU_MAINMENU_CONPONENT_NAME "MainMenuBK"
#define MAINMENU_BUTTON_CONPONENT	"MainMenuButtonBK"
#define MAINMENU_OK_BUTTON_NAME "MainMenuButtonOK"
#define MAINMENU_CANCEL_BUTTON_NAME "MainMenuButtonCancel"
#define	COMM_MAINMENU_BUTTON_CONPONENT       4000
#define COMM_MAINMENU_ENDTURN_OK       4001
#define COMM_MAINMENU_ENDGAME_OK       4002
#define COMM_MAINMENU_SAVEGAME_OK		4003
#define COMM_MAINMENU_LOADGAME_OK		4004
#define COMM_MAINMENU_MAINMENU_CANCEL  4013


//战斗菜单
#define BATTLEMENU_MENU_FILE_NAME  Icon//"BattleMenu"  //战斗菜单文件名
#define	BATTLEMENU_MENU_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,BATTLEMENU_MENU_FILE_NAME))
#define BATTLEMENU_ATK_ICON_NAME  "atk" //攻击指令图标名
#define BATTLEMENU_DEF_ICON_NAME  "def"//防御指令图标名
#define BATTLEMENU_ITEM_ICON_NAME "item"//物品指令图标名
#define BATTLEMENU_SKILL_ICON_NAME "skill"//技能指令图标名
#define BATTLEMENU_MOVE_ICON_NAME  "move"//移动指令图标名
#define BATTLEMENU_STAY_ICON_NAME  "stay"//待机指令图标名
#define BATTLEMENU_STATUS_ICON_NAME "status"//查看角色状态图标名
#define BATTLEMENU_BACK_ICON_NAME  "back"//撤销指令图标名
//定义战斗菜单子项标签
#define BATTLEMENU_SKILL_FILE_NAME Icon//"skillIcons"
#define	BATTLEMENU_SKILL_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,BATTLEMENU_SKILL_FILE_NAME))
//#define BATTLEMENU_SKILL_FIRE_ICON "fire"
//#define BATTLEMENU_SKILL_ICE_ICON "ice"
//#define BATTLEMENU_SKILL_THUNDER_ICON "thunder"




//显示角色状态菜单
#define SHOWSTATUS_MENU_FILE_NAME ShowStatus
#define SHOWSTATUS_MENU_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,SHOWSTATUS_MENU_FILE_NAME))

////回合经过展示层
#define TURNPASS_LAYER_FILE_NAME BattleTurnPass
#define TURNPASS_LAYER_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,TURNPASS_LAYER_FILE_NAME))
#define TURNPASS_PLAYER_LABEL_NAME "PlayerTurnLabel"
#define TURNPASS_PLAYER_MARK_NAME "PlayerTurnMark"
#define TURNPASS_ENERMY_LABEL_NAME "EnermyTurnLabel"
#define TURNPASS_ENERMY_MARK_NAME "EnermyTurnMark"
#define TURNPASS_BLINK_BK_FRAME_NAMEHEAD "TurnPassBlink"
#define TURNPASS_BLINK_BK_FRAME_COUNT  3
#define TURNPASS_BK_BAR_NAME "TurnPassBar"
#define LEVELUP_LOGO_NAME "LevelUp"
//确认范围菜单
#define RANGEMENU_LAYER_FILE_NAME ShowRangeMenu
#define RANGEMENU_LAYER_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,RANGEMENU_LAYER_FILE_NAME))
#define RANGEMENU_BACKGROUND_NAME "showRangeBK"
#define RANGEMENU_OK_BUTTON_NAME "showRangeOK"
#define RANGEMENU_CANCEL_BUTTON_NAME "showRangeCancel"
#define RANGEMENU_RESET_BUTTON_NAME "showRangeReset"
#define RANGEMENU_SUBRANGE_X_NAME "subRange"
#define RANGEMENU_SUBRANGE_1X_NAME "subRange1"
#define RANGEMENU_SUBRANGE_2X_NAME "subRange2"
#define RANGEMENU_SUBRANGE_3X_NAME "subRange3"

#define SQUARE_LENTH (64) 


//unsigned int型数据最多的位数
#define INT_FLITER 1e9
//数字图片资源路径
#define NUMS_FILE_NAME Nums
#define NUMS_FILE_FULLPATH  FULLPATH_STR(PATH_ATTACH(UI_FILE_PATH,NUMS_FILE_NAME))
//字体标识
#define NUMS_SMALL_BLACK "sb"  //黑色小型数字
#define NUMS_MID_BLACK "mb"	//黑色中型数字
#define NUMS_BIG_BLACK "bb" //黑色大型数字
#define NUMS_SMALL_RED "rs" //红色小型数字


//定义数字前后间隔
#define NUMS_SMALL_DISTANCE 10
#define NUMS_MID_DISTANCE 14
#define NUMS_BIG_DISTANCE 18
//地图数字精灵下降时间
#define NUMS_MAPFALL_DUR 0.6f
//决斗场景数字精灵下降时间
#define NUMS_DUELFALL_DUR 0.4f
//数字精灵渐隐时间
#define NUMS_FADEOUT_DUR 0.4f
//LevelUp图标动画持续时间
#define LEVELUP_LOGO_MOVE_DUR 0.3f

//定义阻塞游戏进程的Action Tag
#define ACTION_TAG_BLOCK  1001


#endif